### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by 8hachi8** [8hachi8/chat-space#12]
# IPアドレス
3.114.43.9

**Comment by mo1015** [comment]
齋藤さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

**○ グループに参加した後、1度リロードをしないと自動更新されない**
グループに参加してから1度リロードしないと自動更新が行われません。
リロードしなくても自動更新されるよう修正をお願いします！
※実際に動作をご確認いただく場合は新しく作成したチャットグループで
試してみていただけるといいかと思います。

参考カリキュラム：https://master.tech-camp.in/curriculums/1211

修正でき次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by 8hachi8** [comment]
グループを作成した際にそこのグループのメッセージページにリダイレクトしていればいいということでしょうか？
訂正しましたので確認お願いします。

**Comment by yasunamiura** [comment]
再提出ありがとうございます！
結論、齋藤様にレビュワーの修正する箇所が正確に伝わっておりませんでした。お手数おかけしてしまい大変申し訳ありませんでした。
以下、再度修正いただけると幸いです。

[修正箇所]
**グループを作成して１回目のメッセージ送信で自動更新ができるようにしましょう**
<img width="1431" alt="ChatSpace_と_ChatSpace" src="https://user-images.githubusercontent.com/52514431/84609907-b4185180-aef3-11ea-8058-4e876d46c9da.png">
<img width="1423" alt="ChatSpace_と_ChatSpace" src="https://user-images.githubusercontent.com/52514431/84610027-2a1cb880-aef4-11ea-8f17-9f08c89781db.png">


修正し次第、以下のChatSpace完了報告フォームに再度こちらのissueのURLを記載していただき提出お願いします！
※新しいissueを作っていただく必要はありません
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by 8hachi8** [comment]
申し訳ありません、勘違いしておりました
。
訂正いたしましたので、再度挙動確認のほどお願いいたします。

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！
※今後実装に関する質問がありましたら、メンターに確認をお願いします！

**Comment by 8hachi8** [comment]
ありがとうございます！
引き続きよろしくお願いします。
